### PR TITLE
fix for ghc-9

### PR DESCRIPTION
**Pull request by larskuhtz**

### CODE REVIEW

**Comment by larskuhtz** [comment]
ping

**Comment by ocharles** [comment]
@ivan-m could you merge this? Alternatively, could you grant me merge rights and I'll take over?

**Comment by ivan-m** [comment]
Does this require a release now or is there likely additional changes that might be needed?

**Comment by ocharles** [comment]
With this a release will be fine

**Comment by ivan-m** [comment]
Released as 0.3.0.0, including updates for streaming-bytestring

**Pull request merged**
